export const LOGIN_USERNAME = 'LOGIN_USERNAME';
export const LOGIN_PASSWORD = 'LOGIN_PASSWORD';
export const STORE_TITLE = 'STORE_TITLE';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';

export const ADD_ITEM_PRACTICE = 'ADD_ITEM_PRACTICE';
export const REMOVE_ITEM_FROM_CART_PRACTICE = 'REMOVE_ITEM_FROM_CART_PRACTICE';
export const COMPLETE_ITEM_REMOVE = 'COMPLETE_ITEM_REMOVE';

export const ADD_BTN_VISIBLE = 'ADD_BTN_VISIBLE';
export const ADD_ITEM_TO_WISHLIST = 'ADD_ITEM_TO_WISHLIST';
export const REMOVE_ITEM_FROM_WISHLIST = 'REMOVE_ITEM_FROM_WISHLIST';

export const SET_CART_EMPTY = 'SET_CART_EMPTY';
